local wk = require("which-key")
wk.add({
  { "<leader>.",  "<cmd>Telescope find_files<cr>",     desc = "Find File" },
  { "<leader>/",  "<cmd>Telescope live_grep_args<cr>", desc = "Search File" },
  { "<leader>f",  group = "file" },
  { "<leader>fp", "<cmd>Telescope live_grep_args<cr>", desc = "Search File",                 mode = "n" },
  { "<leader>fr", "<cmd>Telescope oldfiles<cr>",       desc = "Open Recent File",            mode = "n" },
  { "<leader>fd", "<cmd>Neotree reveal<cr>",           desc = "Open directory",              mode = "n" },
  { "<leader>b",  group = "buffer" },
  { "<leader>bi", "<cmd>Telescope buffers<cr>",        desc = "All buffers",                 mode = "n" },
  { "<leader>b[", "<cmd>bp<cr>",                       desc = "Previous buffer",             mode = "n" },
  { "<leader>b]", "<cmd>bn<cr>",                       desc = "Next buffer",                 mode = "n" },
  { "<leader>w",  group = "window" },
  { "<leader>wv", "<c-w>v",                            desc = "Vertically split windows",    mode = "n" },
  { "<leader>ww", "<c-w>p",                            desc = "Switch to other window",      mode = "n" },
  { "<leader>wd", "<c-w>q",                            desc = "Delete window",               mode = "n" },
  { "<leader>q",  group = "quit" },
  { "<leader>qq", "<cmd>qa<cr>",                       desc = "Quit all",                    mode = "n" },
  { "<leader>g",  group = "git" },
  { "<leader>gg", "<cmd>Neogit<cr>",                   desc = "Neogit",                      mode = "n" },
  { "<leader>o",  group = "open" },
  { "<leader>om", "<cmd>Mason<cr>",                    desc = "Mason",                       mode = "n" },
  { "<leader>s",  group = "search" },
  { "<leader>sq", "<cmd>nohl<cr>",                     desc = "Clear search highlight" },
  { "<leader>c",  group = "code" },
  { "<leader>ca", vim.lsp.buf.code_action,             desc = "LSP Code Actions" },
  { "<leader>ck", vim.lsp.buf.hover,                   desc = "Show documentation at cursor" }
})
